import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { Footer } from "./components/Footer";
import { Topbar } from "./components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="gap-4 flex flex-col h-screen">
        <header className="px-16 py-4">
          <Topbar />
        </header>
        <hr className="h-[0.5] shrink-0 bg-gray-300 border-0 w-full" />
        <div className="grow px-8 sm:px-16 py-4 sm:py-8 ">{children}</div>
        <footer className="py-8 px-8 w-full flex justify-center">
          {<Footer />}
        </footer>
      </body>
    </html>
  );
}
